"""
Mapping between bank tickers, FDIC certificate numbers, and SEC CIK numbers.

Lookup order (BANK_MAP wins over JSON wins over live resolver):
  1. BANK_MAP below — hand-curated overrides for collisions, edge cases,
     and known mis-matches the resolver gets wrong.
  2. data/bank_map_resolved.json — auto-generated by
     tools/resolve_all_mappings.py for every universe ticker.
  3. resolve_ticker() — live SEC + FDIC API lookups, cached in process.

To add a bank: prefer the JSON (re-run the resolver) OR add a BANK_MAP
entry for one-off corrections.
"""

import json
import os
import requests
from pathlib import Path


# Auto-generated resolved mappings (committed to repo; rebuilt via
# tools/resolve_all_mappings.py). Loaded once at import.
_RESOLVED_PATH = Path(__file__).parent / "bank_map_resolved.json"
try:
    _RESOLVED_FROM_JSON: dict[str, dict] = (
        json.loads(_RESOLVED_PATH.read_text(encoding="utf-8"))
        if _RESOLVED_PATH.exists() else {}
    )
except Exception as e:
    print(f"[bank_mapping] Failed to load {_RESOLVED_PATH.name}: {e}")
    _RESOLVED_FROM_JSON = {}

# ── Static mapping ──────────────────────────────────────────────────────
# Format: ticker -> {name, fdic_cert, cik}
# fdic_cert: FDIC certificate number (for Call Report data)
# cik: SEC Central Index Key (for EDGAR filings)
BANK_MAP = {
    # ── User watchlist banks ────────────────────────────────────────────
    "SFST":  {"name": "Southern First Bancshares",          "fdic_cert": 35295,  "cik": 1090009},
    "CFFI":  {"name": "C&F Financial Corp.",                "fdic_cert": 10363,  "cik": 913341},
    "CBNK":  {"name": "Capital Bancorp Inc.",               "fdic_cert": 35278,  "cik": 1419536},
    "FBIZ":  {"name": "First Business Financial Services",  "fdic_cert": 15229,  "cik": 1521951},
    "CCBG":  {"name": "Capital City Bank Group",            "fdic_cert": 9622,   "cik": 726601},
    "IBOC":  {"name": "International Bancshares Corp.",     "fdic_cert": 19629,  "cik": 315709},
    "CARE":  {"name": "Carter Bankshares Inc.",             "fdic_cert": 58596,  "cik": 1829576},
    "RNST":  {"name": "Renasant Corp.",                     "fdic_cert": 12437,  "cik": 715072},
    "HTB":   {"name": "HomeTrust Bancshares",               "fdic_cert": 27677,  "cik": 1538263},
    "FRBA":  {"name": "First Bank (NJ)",                    "fdic_cert": 58481,  "cik": None},
    "SMBK":  {"name": "SmartFinancial Inc.",                "fdic_cert": 58463,  "cik": 1038773},
    "BFST":  {"name": "Business First Bancshares",          "fdic_cert": 58228,  "cik": 1624322},
    "TCBX":  {"name": "Third Coast Bancshares",             "fdic_cert": 58716,  "cik": 1781730},
    "FMBH":  {"name": "First Mid Bancshares",               "fdic_cert": 3705,   "cik": 700565},
    "HBNC":  {"name": "Horizon Bancorp Inc.",               "fdic_cert": 14327,  "cik": 706129},
    "PLBC":  {"name": "Plumas Bancorp",                     "fdic_cert": 23275,  "cik": 1168455},
    # FSRL is "First Reliance Bancshares" (not First Savings Financial).
    # OTC-only, no SEC XBRL. FDIC cert 35214 = First Reliance Bank, SC.
    "FSRL":  {"name": "First Reliance Bancshares, Inc.",    "fdic_cert": 35214,  "cik": None},
    # TowneBank files its periodic reports with the Federal Reserve under
    # Securities Exchange Act §12(i) (it's a VA state bank that is its own
    # holding company), so it is ABSENT from SEC's company_tickers.json /
    # EDGAR entirely — the universe builder seeds candidates from that file,
    # so TOWN was never discovered. FDIC-only coverage (cert 35095 = TowneBank,
    # Portsmouth VA, ~$22B assets); SEC-XBRL HoldCo metrics correctly n/a.
    "TOWN":  {"name": "TowneBank",                          "fdic_cert": 35095,  "cik": None},
    # ── §12(i) / SEC-index gap banks (sweep 2026-06-30) ──────────────────
    # 47 publicly-traded US banks ≥$150M mkt cap that were absent from the
    # universe because SEC's company_tickers.json (the discovery seed) omits
    # them — either they file with the Fed/FDIC/OCC under §12(i) (no SEC
    # filings → FDIC-only, cik=None) or they self-file 10-Ks but their OTC
    # ticker isn't in SEC's exchange index (seeding gap → cik present, full
    # coverage). Every fdic_cert verified ACTIVE against the live institution
    # and matched on holding-company name; FXLG (FS Bancorp NM) deferred — no
    # confident active match. See TOWN above for the canonical case.
    "FINN":    {"name": "First National of Nebraska, Inc.",              "fdic_cert": 5452,   "cik": None},
    "UNPA":    {"name": "UNB Corp.",                                     "fdic_cert": 7631,   "cik": None},
    "FMBL":    {"name": "Farmers & Merchants Bank of Long Beach",        "fdic_cert": 1225,   "cik": None},
    "NBN":     {"name": "Northeast Bank",                                "fdic_cert": 19690,  "cik": 811831},
    "WTBFB":   {"name": "W.T.B. Financial Corporation",                  "fdic_cert": 1281,   "cik": None},
    "SBNC":    {"name": "Southern BancShares (N.C.), Inc.",              "fdic_cert": 15359,  "cik": None},
    "FFMR":    {"name": "First Farmers Financial Corporation",           "fdic_cert": 12839,  "cik": None},
    "HIFS":    {"name": "Hingham Institution for Savings",               "fdic_cert": 90211,  "cik": None},
    "THVB":    {"name": "Thomasville Bancshares, Inc.",                  "fdic_cert": 34068,  "cik": None},
    "AMBZ":    {"name": "American Business Bank",                        "fdic_cert": 34788,  "cik": None},
    "RCBC":    {"name": "River City Bank",                               "fdic_cert": 18983,  "cik": None},
    "WCCB":    {"name": "West Coast Community Bancorp",                  "fdic_cert": 57591,  "cik": None},
    "DBIN":    {"name": "Dacotah Banks, Inc.",                           "fdic_cert": 17437,  "cik": None},
    "PBAM":    {"name": "Private Bancorp of America, Inc.",              "fdic_cert": 58291,  "cik": None},
    "FAHE":    {"name": "The Fahey Banking Company",                     "fdic_cert": 2068,   "cik": None},
    "SNLC":    {"name": "Security National Corporation",                 "fdic_cert": 19213,  "cik": None},
    "BFCC":    {"name": "BankFirst Capital Corporation",                 "fdic_cert": 8870,   "cik": None},
    "MFGI":    {"name": "Merchants Financial Group, Inc.",               "fdic_cert": 8866,   "cik": None},
    "MSBC":    {"name": "Mission Bancorp",                               "fdic_cert": 34805,  "cik": None},
    "CYFL":    {"name": "Century Financial Corporation",                 "fdic_cert": 28362,  "cik": None},
    "CSHX":    {"name": "Cashmere Valley Bank",                          "fdic_cert": 1265,   "cik": None},
    "NASB":    {"name": "NASB Financial, Inc.",                          "fdic_cert": 29708,  "cik": 1059131},
    "EXSR":    {"name": "Exchange Bank (Santa Rosa, CA)",                "fdic_cert": 8468,   "cik": None},
    "LRBI":    {"name": "Lake Ridge Bancorp Inc.",                       "fdic_cert": 15091,  "cik": None},
    "TRUX":    {"name": "Truxton Corporation",                           "fdic_cert": 57825,  "cik": None},
    "FFBB":    {"name": "FFB Bancorp",                                   "fdic_cert": 58090,  "cik": None},
    "FFMH":    {"name": "First Farmers and Merchants Corporation",       "fdic_cert": 1487,   "cik": 703329},
    "MLGF":    {"name": "Malaga Financial Corporation",                  "fdic_cert": 32282,  "cik": None},
    "CBTN":    {"name": "Citizens Bancorp Investment, Inc.",             "fdic_cert": 1711,   "cik": None},
    "PSBQ":    {"name": "PSB Holdings, Inc.",                            "fdic_cert": 18569,  "cik": None},
    "HONT":    {"name": "Honat Bancorp, Inc.",                           "fdic_cert": 7526,   "cik": None},
    "SABK":    {"name": "South Atlantic Bancshares, Inc.",               "fdic_cert": 58689,  "cik": None},
    "LYBC":    {"name": "Lyons Bancorp Inc.",                            "fdic_cert": 7151,   "cik": None},
    "BKGM":    {"name": "BankGuam Holding Co.",                          "fdic_cert": 20884,  "cik": None},
    "PLQC":    {"name": "Plains Acquisition Corporation",                "fdic_cert": 17739,  "cik": None},
    "PFLC":    {"name": "Pacific Financial Corporation",                 "fdic_cert": 17308,  "cik": None},
    "MNAT":    {"name": "Marquette National Corporation",                "fdic_cert": 16250,  "cik": None},
    "SBKO":    {"name": "Summit Bank Group, Inc.",                       "fdic_cert": 57706,  "cik": None},
    "UBAB":    {"name": "United Bancorporation of Alabama, Inc.",        "fdic_cert": 58,     "cik": 704561},
    "TRCY":    {"name": "Tri City Bankshares Corporation",               "fdic_cert": 18922,  "cik": 313337},
    "SFIGA":   {"name": "STAR Financial Group, Inc.",                    "fdic_cert": 27235,  "cik": None},
    "TYCB":    {"name": "Calvin B. Taylor Bankshares, Inc.",             "fdic_cert": 5874,   "cik": 1003986},
    "MSWV":    {"name": "Main Street Financial Services Corp.",          "fdic_cert": 29847,  "cik": None},
    "BKUTK":   {"name": "Bank of Utica",                                 "fdic_cert": 13397,  "cik": None},
    "ARBV":    {"name": "American Riviera Bancorp",                      "fdic_cert": 58281,  "cik": None},
    "PBNC":    {"name": "PB Financial Corporation",                      "fdic_cert": 58239,  "cik": None},
    "PONT":    {"name": "Pontiac Bancorp, Inc.",                         "fdic_cert": 16982,  "cik": None},
    "BANR":  {"name": "Banner Corp.",                       "fdic_cert": 28489,  "cik": 946673},
    # MCBI (Mountain Commerce Bancshares) was acquired 04/01/2026 — FDIC
    # cert 4931 is ACTIVE=0. The universe filter would drop it anyway via
    # cert_is_active() in data/fdic_client.py, but keeping it here as an
    # explicit None signals "we know about this; intentionally excluded".
    "MCBI":  {"name": "Mountain Commerce Bancshares (acquired)", "fdic_cert": None, "cik": None},
    "BRBS":  {"name": "Blue Ridge Bankshares",              "fdic_cert": 17773,  "cik": 842717},
    "FSBW":  {"name": "FS Bancorp Inc.",                    "fdic_cert": 57633,  "cik": 1530249},
    "SPFI":  {"name": "South Plains Financial Inc.",        "fdic_cert": 25103,  "cik": 1163668},
    "ALRS":  {"name": "Alerus Financial Corp.",             "fdic_cert": 3931,   "cik": 903419},
    "FMNB":  {"name": "Farmers National Banc Corp.",        "fdic_cert": 3732,   "cik": 709337},
    "HFWA":  {"name": "Heritage Financial Corp.",           "fdic_cert": 29012,  "cik": 1046025},
    "BAFN":  {"name": "BayFirst Financial Corp.",           "fdic_cert": 34997,  "cik": 1649739},
    "CBAN":  {"name": "Colony Bankcorp Inc.",               "fdic_cert": 22257,  "cik": 711669},
    "OVBC":  {"name": "Ohio Valley Banc Corp.",             "fdic_cert": 384,    "cik": 894671},
    "FRME":  {"name": "First Merchants Corp.",              "fdic_cert": 4365,   "cik": 712534},
    # LINKBANCORP's sub is LINKBANK (cert 14863). Cert 9889 is Mid Penn Bank.
    "LNKB":  {"name": "LINKBANCORP Inc.",                   "fdic_cert": 14863,  "cik": 1756701},
    "WAL":   {"name": "Western Alliance Bancorporation",    "fdic_cert": 57512,  "cik": 1212545},
    "TSBK":  {"name": "Timberland Bancorp",                 "fdic_cert": 28453,  "cik": 1046050},
    "BKU":   {"name": "BankUnited Inc.",                    "fdic_cert": 58979,  "cik": 1504008},
    "PGC":   {"name": "Peapack-Gladstone Financial",        "fdic_cert": 11035,  "cik": 1050743},
    "SBFG":  {"name": "SB Financial Group",                 "fdic_cert": 13339,  "cik": 767405},
    "FNWB":  {"name": "First Northwest Bancorp",            "fdic_cert": 28405,  "cik": 1556727},
    "INBC":  {"name": "Independent Bank Corp.",             "fdic_cert": 9712,   "cik": None},
    "CCNB":  {"name": "Coastal Carolina Bancshares",        "fdic_cert": 58864,  "cik": 1437213},
    "JMSB":  {"name": "John Marshall Bancorp",              "fdic_cert": 58243,  "cik": 1710482},
    "RVSB":  {"name": "Riverview Bancorp Inc.",             "fdic_cert": 29922,  "cik": 1041368},
    "SLBK":  {"name": "Skyline Bankshares",                 "fdic_cert": 6861,   "cik": 1657642},
    "INBK":  {"name": "First Internet Bancorp",             "fdic_cert": 34607,  "cik": 1562463},
    "RMBI":  {"name": "Richmond Mutual Bancorporation",     "fdic_cert": 28533,  "cik": 1767837},
    "TFSL":  {"name": "TFS Financial Corp.",                "fdic_cert": 30012,  "cik": 1381668},
    "CBK":   {"name": "Commercial Bancgroup Inc.",          "fdic_cert": None,   "cik": 1981546},
    # IBTN is "InsCorp, Inc." (not iBank Financial). OTC-only, no SEC XBRL.
    # FDIC cert 35521 = InsBank, holdco INSCORP INC, TN.
    "IBTN":  {"name": "InsCorp, Inc.",                      "fdic_cert": 35521,  "cik": None},
    "FGBI":  {"name": "First Guaranty Bancshares",          "fdic_cert": 14028,  "cik": 1408534},
    "PNFP":  {"name": "Pinnacle Financial Partners",        "fdic_cert": 35583,  "cik": 2082866},
    # OTC-traded community bank — not in SEC's exchange-listed tickers.json
    # but trades as CMHF with CIK 1792597 (sub-bank: Middletown Valley Bank MD)
    "CMHF":  {"name": "Community Heritage Financial, Inc.",  "fdic_cert": 14017,  "cik": 1792597},
    # Bank OZK is a National Bank (no holding company) — files Call Reports
    # with FFIEC only, no SEC XBRL filings. cik=None forces FDIC-only path.
    "OZK":   {"name": "Bank OZK",                           "fdic_cert": 110,    "cik": None},
    "FHN":   {"name": "First Horizon Corp.",                "fdic_cert": 4977,   "cik": 36966},
    "UBSI":  {"name": "United Bankshares Inc.",             "fdic_cert": 22858,  "cik": 729986},
    "FBNC":  {"name": "First Bancorp (NC)",                 "fdic_cert": 15019,  "cik": 811589},
    "FFWM":  {"name": "First Foundation Inc.",              "fdic_cert": 58647,  "cik": 1413837},
    "FFIN":  {"name": "First Financial Bankshares",         "fdic_cert": 19440,  "cik": 36029},
    "HOMB":  {"name": "Home BancShares Inc.",               "fdic_cert": 11241,  "cik": 1331520},
    "EGBN":  {"name": "Eagle Bancorp Inc.",                 "fdic_cert": 34742,  "cik": 1050441},
    "ISBA":  {"name": "Isabella Bank Corp.",                "fdic_cert": 1005,   "cik": 842517},
    "BANC":  {"name": "Banc of California Inc.",            "fdic_cert": 24045,  "cik": 1169770},
    "FLG":   {"name": "Flagstar Financial Inc.",            "fdic_cert": 32541,  "cik": 910073},
    "VLY":   {"name": "Valley National Bancorp",            "fdic_cert": 9396,   "cik": 714310},
    "KEY":   {"name": "KeyCorp",                            "fdic_cert": 17534,  "cik": 91576},
    "HBAN":  {"name": "Huntington Bancshares",              "fdic_cert": 6560,   "cik": 49196},
    "ZION":  {"name": "Zions Bancorporation",               "fdic_cert": 2270,   "cik": 109380},
    "FNB":   {"name": "FNB Corp.",                          "fdic_cert": 2107,   "cik": 37808},
    # OZK is defined above as cik=None (National Bank, no SEC XBRL).
    # Cert 32469 is UCBH's failed predecessor. East West Bank's real cert is 31628.
    # CIK 806279 was wrong (another entity). Official SEC CIK for EWBC is 1069157.
    "EWBC":  {"name": "East West Bancorp",                  "fdic_cert": 31628,  "cik": 1069157},
    "CATY":  {"name": "Cathay General Bancorp",             "fdic_cert": 18503,  "cik": 861842},
    # Post-Umpqua merger (Mar 2023) the official SEC CIK is 887343, not 1166928.
    "COLB":  {"name": "Columbia Banking System",            "fdic_cert": 17266,  "cik": 887343},
    "BOKF":  {"name": "BOK Financial Corp.",                "fdic_cert": 4214,   "cik": 875357},
    "BOH":   {"name": "Bank of Hawaii Corp.",               "fdic_cert": 18053,  "cik": 46195},

    # OTC-traded thrift: SEC CIK 942895 has no XBRL data, files only D + 13G.
    # FDIC cert 31028 = HomeTown Bank, MN (holdco REDWOOD FINANCIAL INC).
    "REDW":  {"name": "Redwood Financial Inc /MN/",         "fdic_cert": 31028,  "cik": None},

    # ── Small/thrift banks where the dynamic FDIC resolver mis-matches ──
    # These names collide with larger banks and the Jaccard-similarity
    # search picks the wrong sub-bank. Hardcoded to prevent regression.
    "IBCP":  {"name": "Independent Bank Corp. (MI)",        "fdic_cert": 27811,  "cik": 39311},    # NOT 9712 (Rockland Trust)
    "FMAO":  {"name": "Farmers & Merchants Bancorp (OH)",   "fdic_cert": 5969,   "cik": 792966},   # NOT 13421 (Union Bank Trust NE)
    "FBLA":  {"name": "FB Bancorp (MD)",                    "fdic_cert": None,   "cik": 2013639},  # Recent IPO; no FDIC match
    "MGNO":  {"name": "Magnolia Bancorp",                   "fdic_cert": None,   "cik": 2033615},  # Recent IPO; no FDIC match

    # ── Large US banks (for reference/comparison) ──────────────────────
    "JPM":   {"name": "JPMorgan Chase & Co.",               "fdic_cert": 628,    "cik": 19617},
    "BAC":   {"name": "Bank of America Corp.",              "fdic_cert": 3510,   "cik": 70858},
    "WFC":   {"name": "Wells Fargo & Co.",                  "fdic_cert": 3511,   "cik": 72971},
    "C":     {"name": "Citigroup Inc.",                     "fdic_cert": 7213,   "cik": 831001},
    "USB":   {"name": "U.S. Bancorp",                       "fdic_cert": 6548,   "cik": 36104},
    "PNC":   {"name": "PNC Financial Services",             "fdic_cert": 6384,   "cik": 713676},
    "TFC":   {"name": "Truist Financial Corp.",              "fdic_cert": 9846,   "cik": 92230},
    "COF":   {"name": "Capital One Financial",               "fdic_cert": 4297,   "cik": 927628},
    "GS":    {"name": "Goldman Sachs Group",                 "fdic_cert": 33124,  "cik": 886982},
    "MS":    {"name": "Morgan Stanley",                      "fdic_cert": 32992,  "cik": 895421},
}


# ── IR page URLs (separate to keep BANK_MAP clean) ──────────────────────
# Maps ticker -> investor relations URL. Not every bank is listed; the UI
# falls back to the SEC EDGAR company page when missing.
IR_URLS = {
    "PFS":   "https://investorrelations.provident.bank/",
    "SFST":  "https://www.southernfirst.com/investor-relations",
    "CFFI":  "https://www.cffc.com/investor-relations/",
    "CBNK":  "https://ir.capitalbankmd.com/",
    "FBIZ":  "https://ir.firstbusiness.bank/",
    "CCBG":  "https://www.ccbg.com/investor-relations/",
    "IBOC":  "https://www.ibc.com/investors",
    "CARE":  "https://www.carterbankshares.com/investor-relations/",
    "RNST":  "https://investors.renasant.com/",
    "HTB":   "https://ir.htb.com/",
    "SMBK":  "https://ir.smartfinancialinc.com/",
    "BFST":  "https://ir.b1bank.com/",
    "TCBX":  "https://ir.thirdcoast.bank/",
    "FMBH":  "https://www.firstmidbancshares.com/investor-relations/",
    "HBNC":  "https://investor.horizonbank.com/",
    "PLBC":  "https://www.plumasbank.com/investor-relations",
    "BANR":  "https://www.bannerbank.com/investor-relations",
    "BRBS":  "https://www.mybrb.com/investor-relations/",
    "FSBW":  "https://ir.fsbwa.com/",
    "SPFI":  "https://ir.southplains.com/",
    "ALRS":  "https://ir.alerus.com/",
    "FMNB":  "https://www.farmersbankgroup.com/investor-relations",
    "HFWA":  "https://ir.hf-wa.com/",
    "CBAN":  "https://ir.colony.bank/",
    # Q4 IR site the nightly subdomain probe should have found off the FDIC
    # webaddr but didn't (missing/mismatched webaddr or a transient Q4-detect
    # miss). Curated as the reliable fix — without it CBSH's first-party releases
    # (the Nolan acquisition, dividends, buybacks) reached only Google News,
    # which the Home feed hides. Verified: Q4 API returns the releases.
    "CBSH":  "https://investor.commercebank.com/",
    "FRME":  "https://www.firstmerchants.com/investor-relations",
    "WAL":   "https://ir.westernalliancebancorporation.com/",
    "BKU":   "https://ir.bankunited.com/",
    "PGC":   "https://www.pgbank.com/investor-relations",
    "INBK":  "https://ir.firstib.com/",
    "FGBI":  "https://www.firstguaranty.com/investor-relations",
    "PNFP":  "https://ir.pnfp.com/",
    "OZK":   "https://ir.ozk.com/",
    "FHN":   "https://ir.firsthorizon.com/",
    "UBSI":  "https://www.ubsi-wv.com/investor-relations",
    "FBNC":  "https://ir.localfirstbank.com/",
    "FFWM":  "https://ir.firstfoundationinc.com/",
    "FFIN":  "https://www.ffin.com/investor-relations",
    "HOMB":  "https://ir.homebancshares.com/",
    "EGBN":  "https://ir.eaglebankcorp.com/",
    "BANC":  "https://ir.bancofcal.com/",
    "FLG":   "https://ir.flagstar.com/",
    "VLY":   "https://www.valley.com/investor-relations",
    "KEY":   "https://ir.key.com/",
    "HBAN":  "https://ir.huntington.com/",
    "ZION":  "https://www.zionsbancorporation.com/investor-relations",
    "JPM":   "https://www.jpmorganchase.com/ir",
    "BAC":   "https://investor.bankofamerica.com/",
    "WFC":   "https://www.wellsfargo.com/about/investor-relations/",
    "C":     "https://www.citigroup.com/global/investors",
    "USB":   "https://ir.usbank.com/",
    "PNC":   "https://investor.pnc.com/",
    "TFC":   "https://ir.truist.com/",
    "COF":   "https://ir.capitalone.com/",
    "GS":    "https://www.goldmansachs.com/investor-relations/",
    "MS":    "https://www.morganstanley.com/about-us-ir",
}


def get_ir_url(ticker: str) -> str | None:
    """Return the IR page URL for a ticker, or None if unknown."""
    return IR_URLS.get(ticker.upper())


def get_bank_info(ticker: str) -> dict | None:
    """Return bank info dict for a ticker, same priority order as
    get_fdic_cert(). Live resolution is the LAST resort — it makes network
    calls and must never run for tickers the snapshot already covers."""
    ticker = ticker.upper()
    info = (BANK_MAP.get(ticker) or _RESOLVED_FROM_JSON.get(ticker)
            or _universe_snapshot_map().get(ticker) or _RESOLVED_CACHE.get(ticker))
    if info:
        return info
    resolved = resolve_ticker(ticker)
    return resolved if resolved.get("cik") or resolved.get("fdic_cert") else None


def get_name(ticker: str) -> str:
    """Return bank display name, same priority order as get_fdic_cert().
    Called per option by the company picker's format_func — a live
    resolution here ran 60+ network lookups per page run (measured: the
    page hung for minutes in search_fdic_by_name).

    Every name is normalized through utils.formatting.format_bank_name so the
    whole dashboard is consistent regardless of which source (ALL-CAPS SEC
    EDGAR, curated Title Case, FDIC with /XX/ suffixes) supplied it."""
    from utils.formatting import format_bank_name  # lazy: keep cold-start light
    ticker = ticker.upper()
    info = (BANK_MAP.get(ticker) or _RESOLVED_FROM_JSON.get(ticker)
            or _universe_snapshot_map().get(ticker) or _RESOLVED_CACHE.get(ticker))
    if info and info.get("name"):
        return format_bank_name(info["name"], ticker)
    resolved = resolve_ticker(ticker)
    return format_bank_name(resolved.get("name", ticker), ticker)


def get_fdic_cert(ticker: str) -> int | None:
    """
    Return FDIC cert number, in priority order:
      1. BANK_MAP (hand-curated overrides — wins even if value is None)
      2. _RESOLVED_FROM_JSON (auto-generated, committed file)
      3. universe snapshot (discovery already verified CIK/cert — one cheap
         DB read per process, no network; rebuilt nightly)
      4. _RESOLVED_CACHE (this-session live resolver results)
      5. resolve_ticker() (live SEC + FDIC lookup)
    """
    ticker = ticker.upper()
    if ticker in BANK_MAP:
        return BANK_MAP[ticker].get("fdic_cert")
    if ticker in _RESOLVED_FROM_JSON:
        return _RESOLVED_FROM_JSON[ticker].get("fdic_cert")
    snap = _universe_snapshot_map()
    if ticker in snap:
        return snap[ticker].get("fdic_cert")
    if ticker in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[ticker].get("fdic_cert")
    resolved = resolve_ticker(ticker)
    return resolved.get("fdic_cert")


def get_cik(ticker: str) -> int | None:
    """Return SEC CIK, in the same priority order as get_fdic_cert()."""
    ticker = ticker.upper()
    if ticker in BANK_MAP:
        return BANK_MAP[ticker].get("cik")
    if ticker in _RESOLVED_FROM_JSON:
        return _RESOLVED_FROM_JSON[ticker].get("cik")
    snap = _universe_snapshot_map()
    if ticker in snap:
        return snap[ticker].get("cik")
    if ticker in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[ticker].get("cik")
    resolved = resolve_ticker(ticker)
    return resolved.get("cik")


# Universe-snapshot lookup tier. Discovery (data/bank_universe.py) verifies
# every ticker's CIK (SEC SIC + US-domicile check) and FDIC cert before
# persisting, so the snapshot is an authoritative resolved store for tickers
# beyond the curated files. Without this tier, each newly discovered bank
# triggered a live per-ticker SEC resolution in EVERY fresh process —
# measured 174s for the universe list on a cold start. Read directly from
# data.cache (not bank_universe) to avoid a circular import.
_SNAPSHOT_MAP: dict[str, dict] | None = None


def _universe_snapshot_map() -> dict[str, dict]:
    global _SNAPSHOT_MAP
    if _SNAPSHOT_MAP is None:
        try:
            from data import cache
            snap = cache.get("bank_universe_lastgood") or {}
            uni = snap.get("universe", snap)  # stamped or legacy format
            _SNAPSHOT_MAP = {
                t: v for t, v in (uni or {}).items() if isinstance(v, dict)
            }
        except Exception as e:
            print(f"[bank_mapping] snapshot tier unavailable: {type(e).__name__}: {e}")
            _SNAPSHOT_MAP = {}
    return _SNAPSHOT_MAP


# ── Runtime cache for dynamically resolved tickers ───────────────────────
# Tickers added at runtime that aren't in BANK_MAP get resolved once
# via SEC/FDIC API lookups and cached here for the session.
_RESOLVED_CACHE: dict[str, dict] = {}


def search_sec_by_ticker(ticker: str) -> tuple[int | None, str | None]:
    """
    Look up SEC CIK and company name by ticker using company_tickers.json.
    Returns (cik, company_name) tuple.
    """
    try:
        url = "https://www.sec.gov/files/company_tickers.json"
        headers = {"User-Agent": "BankValuationDashboard admin@company.com"}
        resp = requests.get(url, headers=headers, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        ticker_upper = ticker.upper()
        for entry in data.values():
            if entry.get("ticker", "").upper() == ticker_upper:
                return entry.get("cik_str"), entry.get("title", "")
        return None, None
    except Exception:
        return None, None


def _clean_name(name: str) -> str:
    """Normalize a holding-company name for matching."""
    if not name:
        return ""
    s = name.upper()
    for suffix in [", INC.", ", INC", " INC.", " INC", " CORP.", " CORP",
                   " CO.", " CO", " LTD.", " LTD", " CORPORATION",
                   " HOLDINGS", " FINANCIAL", " BANCORP", " BANCORPORATION",
                   " GROUP", " LLC", "/DE", "/MD", "/NJ", "/RI", "/PA", "/OH", "/NC"]:
        s = s.replace(suffix, "")
    # Strip punctuation
    for p in [",", ".", "'", "&"]:
        s = s.replace(p, " ")
    return " ".join(s.split())  # collapse multi-space


def _name_similarity(a: str, b: str) -> float:
    """
    Jaccard similarity of cleaned-name word sets. 1.0 = identical word set.
    Avoids 'starts-with' false positives that matched everything to BAC.
    """
    wa = set(_clean_name(a).split())
    wb = set(_clean_name(b).split())
    if not wa or not wb:
        return 0.0
    # Ignore trivial words that match everything
    trivial = {"BANK", "BANKS", "BK", "BANCORP", "BANCORPORATION",
               "THE", "A", "AN", "OF"}
    wa -= trivial
    wb -= trivial
    if not wa or not wb:
        # If both names are only trivial words, fall back to exact-ish match
        return 1.0 if _clean_name(a) == _clean_name(b) else 0.0
    return len(wa & wb) / len(wa | wb)


def search_fdic_by_name(name: str, min_similarity: float = 0.5) -> int | None:
    """
    Search FDIC for the primary bank subsidiary CERT matching a holding-
    company name.

    Strategy:
      1. Build 1-3 quoted-phrase queries from the cleaned name (the FDIC API
         treats bare spaces as OR, so we MUST quote phrases to search exact
         substrings).
      2. Run each query against the FDIC institutions endpoint (sorted by
         ASSET DESC) and collect candidate banks.
      3. Score each candidate by name similarity to the query.
      4. Return the highest-similarity match above `min_similarity`;
         otherwise return None rather than wire up the wrong cert.

    This replaces an earlier implementation that did a single-word wildcard
    search which silently fell through to BAC (cert=3510) for many small banks.
    """
    if not name:
        return None

    import urllib.parse

    try:
        clean = _clean_name(name)
        if not clean:
            return None
        words = clean.split()

        # Build candidate quoted phrases in order of specificity.
        # For "ATLANTIC UNION BANKSHARES" we'd try:
        #   "ATLANTIC UNION BANKSHARES"  (most specific — might not match)
        #   "ATLANTIC UNION"
        #   "ATLANTIC"
        phrases = []
        if len(words) >= 3:
            phrases.append(" ".join(words[:3]))
        if len(words) >= 2:
            phrases.append(" ".join(words[:2]))
        if words:
            # Avoid single-word generic first words that would match too broadly
            generic_singletons = {
                "BANK", "FIRST", "NATIONAL", "AMERICAN", "UNITED", "CITIZENS",
                "COMMUNITY", "PEOPLES", "HERITAGE", "HOME", "CENTRAL",
                "SOUTHERN", "NORTHERN", "EASTERN", "WESTERN", "PACIFIC",
                "SUMMIT", "PREMIER", "INDEPENDENT", "TRUST", "THE",
            }
            if words[0] not in generic_singletons:
                phrases.append(words[0])

        # Dedupe while preserving order
        seen = set(); phrases = [p for p in phrases if not (p in seen or seen.add(p))]

        all_candidates = []
        for phrase in phrases:
            quoted = f'"{phrase}"'
            encoded = urllib.parse.quote(quoted)
            params = {
                "filters": f"NAMEHCR:{encoded}",
                "fields": "CERT,NAME,NAMEHCR,ASSET,ACTIVE",
                "sort_by": "ASSET",
                "sort_order": "DESC",
                "limit": 20,
            }
            try:
                resp = requests.get(
                    "https://banks.data.fdic.gov/api/institutions",
                    params=params, timeout=10,
                )
                resp.raise_for_status()
                for cand in resp.json().get("data", []):
                    all_candidates.append(cand.get("data", {}))
            except Exception:
                continue

            # If the most specific phrase returned a confident match, stop early
            if all_candidates:
                break

        if not all_candidates:
            return None

        # Prefer ACTIVE institutions
        active = [c for c in all_candidates if c.get("ACTIVE") == 1]
        pool = active or all_candidates

        # Score by similarity
        best = None; best_score = 0.0
        for cand in pool:
            cand_name = cand.get("NAMEHCR", "")
            score = _name_similarity(name, cand_name)
            if score > best_score:
                best_score = score
                best = cand

        if best and best_score >= min_similarity:
            return int(best["CERT"])
        return None
    except Exception:
        return None


def resolve_ticker(ticker: str) -> dict:
    """
    Resolve a ticker to full bank info. Uses static map first, then runtime
    cache, then falls back to SEC + FDIC API lookups. Results are cached
    so subsequent calls are instant.

    Returns dict with ticker, name, fdic_cert, cik (any may be None).
    """
    ticker = ticker.upper()

    # 1. Static map
    info = BANK_MAP.get(ticker)
    if info:
        return {"ticker": ticker, **info}

    # 2. Runtime cache
    if ticker in _RESOLVED_CACHE:
        return {"ticker": ticker, **_RESOLVED_CACHE[ticker]}

    # 3. Dynamic resolution
    cik, sec_name = search_sec_by_ticker(ticker)

    # Clean up SEC name to title case
    name = sec_name.title() if sec_name else ticker
    # Fix common title-case issues
    for bad, good in [("'S", "'s"), ("Ii", "II"), ("Iii", "III"),
                      ("Llc", "LLC"), ("N.A.", "N.A.")]:
        name = name.replace(bad, good)

    # Try to find FDIC cert from the SEC company name
    fdic_cert = search_fdic_by_name(sec_name) if sec_name else None

    resolved = {"name": name, "fdic_cert": fdic_cert, "cik": cik}
    _RESOLVED_CACHE[ticker] = resolved
    return {"ticker": ticker, **resolved}
