"""
Mapping between bank tickers, FDIC certificate numbers, and SEC CIK numbers.

Lookup order (BANK_MAP wins over JSON wins over live resolver):
  1. BANK_MAP below — hand-curated overrides for collisions, edge cases,
     and known mis-matches the resolver gets wrong.
  2. data/bank_map_resolved.json — auto-generated by
     tools/resolve_all_mappings.py for every universe ticker.
  3. resolve_ticker() — live SEC + FDIC API lookups, cached in process.

To add a bank: prefer the JSON (re-run the resolver) OR add a BANK_MAP
entry for one-off corrections.
"""

import json
import os
import requests
from pathlib import Path


# Auto-generated resolved mappings (committed to repo; rebuilt via
# tools/resolve_all_mappings.py). Loaded once at import.
_RESOLVED_PATH = Path(__file__).parent / "bank_map_resolved.json"
try:
    _RESOLVED_FROM_JSON: dict[str, dict] = (
        json.loads(_RESOLVED_PATH.read_text(encoding="utf-8"))
        if _RESOLVED_PATH.exists() else {}
    )
except Exception as e:
    print(f"[bank_mapping] Failed to load {_RESOLVED_PATH.name}: {e}")
    _RESOLVED_FROM_JSON = {}

# ── Static mapping ──────────────────────────────────────────────────────
# Format: ticker -> {name, fdic_cert, cik}
# fdic_cert: FDIC certificate number (for Call Report data)
# cik: SEC Central Index Key (for EDGAR filings)
BANK_MAP = {
    # ── User watchlist banks ────────────────────────────────────────────
    "SFST":  {"name": "Southern First Bancshares",          "fdic_cert": 35295,  "cik": 1090009},
    "CFFI":  {"name": "C&F Financial Corp.",                "fdic_cert": 10363,  "cik": 913341},
    "CBNK":  {"name": "Capital Bancorp Inc.",               "fdic_cert": 35278,  "cik": 1419536},
    "FBIZ":  {"name": "First Business Financial Services",  "fdic_cert": 15229,  "cik": 1521951},
    "CCBG":  {"name": "Capital City Bank Group",            "fdic_cert": 9622,   "cik": 726601},
    "IBOC":  {"name": "International Bancshares Corp.",     "fdic_cert": 19629,  "cik": 315709},
    "CARE":  {"name": "Carter Bankshares Inc.",             "fdic_cert": 58596,  "cik": 1829576},
    "RNST":  {"name": "Renasant Corp.",                     "fdic_cert": 12437,  "cik": 715072},
    "HTB":   {"name": "HomeTrust Bancshares",               "fdic_cert": 27677,  "cik": 1538263},
    "FRBA":  {"name": "First Bank (NJ)",                    "fdic_cert": 58481,  "cik": None},
    "SMBK":  {"name": "SmartFinancial Inc.",                "fdic_cert": 58463,  "cik": 1038773},
    "BFST":  {"name": "Business First Bancshares",          "fdic_cert": 58228,  "cik": 1624322},
    "TCBX":  {"name": "Third Coast Bancshares",             "fdic_cert": 58716,  "cik": 1781730},
    "FMBH":  {"name": "First Mid Bancshares",               "fdic_cert": 3705,   "cik": 700565},
    # cert 14327 was Horizon Bank of NEBRASKA ($539M) — a same-name bank in the
    # wrong state, and 14327 carries NO high holder at all, so the NAMEHCR tell
    # had nothing to contradict. Real sub = Horizon Bank, Michigan City IN
    # ($6.54B vs the $6.56B holdco), hcr HORIZON BCORP INC.
    "HBNC":  {"name": "Horizon Bancorp Inc.",               "fdic_cert": 4360,   "cik": 706129},
    "PLBC":  {"name": "Plumas Bancorp",                     "fdic_cert": 23275,  "cik": 1168455},
    # FSRL is "First Reliance Bancshares" (not First Savings Financial).
    # OTC-only, no SEC XBRL. FDIC cert 35214 = First Reliance Bank, SC.
    "FSRL":  {"name": "First Reliance Bancshares, Inc.",    "fdic_cert": 35214,  "cik": None},
    # TowneBank files its periodic reports with the Federal Reserve under
    # Securities Exchange Act §12(i) (it's a VA state bank that is its own
    # holding company), so it is ABSENT from SEC's company_tickers.json /
    # EDGAR entirely — the universe builder seeds candidates from that file,
    # so TOWN was never discovered. FDIC-only coverage (cert 35095 = TowneBank,
    # Portsmouth VA, ~$22B assets); SEC-XBRL HoldCo metrics correctly n/a.
    "TOWN":  {"name": "TowneBank",                          "fdic_cert": 35095,  "cik": None},
    # ── §12(i) / SEC-index gap banks (sweep 2026-06-30) ──────────────────
    # 47 publicly-traded US banks ≥$150M mkt cap that were absent from the
    # universe because SEC's company_tickers.json (the discovery seed) omits
    # them. Every fdic_cert verified ACTIVE against the live institution and
    # matched on holding-company name; FXLG CLOSED 2026-07-10 — verified no
    # confident active match. See TOWN above for the canonical case.
    # ALL cik=None (FDIC-only): these banks stopped filing XBRL with the SEC
    # years ago (2012-2023) — a few keep an old CIK, but its companyfacts is
    # 3-14 yrs stale, so attaching it would show decade-old SEC data instead of
    # fresh FFIEC. The refresh-universe reconciliation gate caught this
    # (2026-07-02: "sec_filings: Data is 3836 days old"). FDIC-only is correct
    # and fresh; SEC-XBRL HoldCo metrics render n/a by design.
    "FINN":    {"name": "First National of Nebraska, Inc.",              "fdic_cert": 5452,   "cik": None},
    "UNPA":    {"name": "UNB Corp.",                                     "fdic_cert": 7631,   "cik": None},
    "FMBL":    {"name": "Farmers & Merchants Bank of Long Beach",        "fdic_cert": 1225,   "cik": None},
    "NBN":     {"name": "Northeast Bank",                                "fdic_cert": 19690,  "cik": None},
    "WTBFB":   {"name": "W.T.B. Financial Corporation",                  "fdic_cert": 1281,   "cik": None},
    "SBNC":    {"name": "Southern BancShares (N.C.), Inc.",              "fdic_cert": 15359,  "cik": None},
    "FFMR":    {"name": "First Farmers Financial Corporation",           "fdic_cert": 12839,  "cik": None},
    "HIFS":    {"name": "Hingham Institution for Savings",               "fdic_cert": 90211,  "cik": None},
    "THVB":    {"name": "Thomasville Bancshares, Inc.",                  "fdic_cert": 34068,  "cik": None},
    "AMBZ":    {"name": "American Business Bank",                        "fdic_cert": 34788,  "cik": None},
    "RCBC":    {"name": "River City Bank",                               "fdic_cert": 18983,  "cik": None},
    "WCCB":    {"name": "West Coast Community Bancorp",                  "fdic_cert": 57591,  "cik": None},
    "DBIN":    {"name": "Dacotah Banks, Inc.",                           "fdic_cert": 17437,  "cik": None},
    "PBAM":    {"name": "Private Bancorp of America, Inc.",              "fdic_cert": 58291,  "cik": None},
    "FAHE":    {"name": "The Fahey Banking Company",                     "fdic_cert": 2068,   "cik": None},
    # THREE different companies are "SECURITY NATIONAL CORP" to the FDIC, in
    # NE, SD and FL. cert 19213 is the NEBRASKA one's bank (Security National
    # Bank of Omaha). SNLC is the South Dakota one (Dakota Dunes) whose lead
    # sub is Security National Bank of Sioux City, IA ($1.74B, hcr state SD);
    # it also owns cert 34394 ($0.25B), so the largest sub is the join, per the
    # ATLO/QCRH convention.
    "SNLC":    {"name": "Security National Corporation",                 "fdic_cert": 4506,   "cik": None},
    "BFCC":    {"name": "BankFirst Capital Corporation",                 "fdic_cert": 8870,   "cik": None},
    "MFGI":    {"name": "Merchants Financial Group, Inc.",               "fdic_cert": 8866,   "cik": None},
    "MSBC":    {"name": "Mission Bancorp",                               "fdic_cert": 34805,  "cik": None},
    # cert 28362 is Century Bank of Santa Fe NEW MEXICO (hcr CENTURY FINL
    # SERVICES CO). CYFL is Century Financial Corporation of Coldwater
    # MICHIGAN — its bank is Century Bank and Trust, same city, hcr CENTURY
    # FINANCIAL CORP [MI].
    "CYFL":    {"name": "Century Financial Corporation",                 "fdic_cert": 5015,   "cik": None},
    "CSHX":    {"name": "Cashmere Valley Bank",                          "fdic_cert": 1265,   "cik": None},
    "NASB":    {"name": "NASB Financial, Inc.",                          "fdic_cert": 29708,  "cik": None},
    "EXSR":    {"name": "Exchange Bank (Santa Rosa, CA)",                "fdic_cert": 8468,   "cik": None},
    "LRBI":    {"name": "Lake Ridge Bancorp Inc.",                       "fdic_cert": 15091,  "cik": None},
    "TRUX":    {"name": "Truxton Corporation",                           "fdic_cert": 57825,  "cik": None},
    "FFBB":    {"name": "FFB Bancorp",                                   "fdic_cert": 58090,  "cik": None},
    "FFMH":    {"name": "First Farmers and Merchants Corporation",       "fdic_cert": 1487,   "cik": None},
    "MLGF":    {"name": "Malaga Financial Corporation",                  "fdic_cert": 32282,  "cik": None},
    "CBTN":    {"name": "Citizens Bancorp Investment, Inc.",             "fdic_cert": 1711,   "cik": None},
    "PSBQ":    {"name": "PSB Holdings, Inc.",                            "fdic_cert": 18569,  "cik": None},
    "HONT":    {"name": "Honat Bancorp, Inc.",                           "fdic_cert": 7526,   "cik": None},
    "SABK":    {"name": "South Atlantic Bancshares, Inc.",               "fdic_cert": 58689,  "cik": None},
    "LYBC":    {"name": "Lyons Bancorp Inc.",                            "fdic_cert": 7151,   "cik": None},
    "BKGM":    {"name": "BankGuam Holding Co.",                          "fdic_cert": 20884,  "cik": None},
    "PLQC":    {"name": "Plains Acquisition Corporation",                "fdic_cert": 17739,  "cik": None},
    # cert 17308 is CENTRAL Pacific Bank (Honolulu, $7.49B) — CPF's sub, not
    # PFLC's. The §12(i) sweep matched on holding-company name alone and
    # "PACIFIC FINANCIAL CORP" is a substring of "CENTRAL PACIFIC FINANCIAL
    # CORP". Until 53aab80 moved CPF onto its own cert the two were exactly
    # SWAPPED (CPF held 23041), so not even the duplicate-cert tell fired.
    # Real sub = Bank of the Pacific, Aberdeen WA, hcr PACIFIC FINANCIAL CORP.
    "PFLC":    {"name": "Pacific Financial Corporation",                 "fdic_cert": 23041,  "cik": None},
    "MNAT":    {"name": "Marquette National Corporation",                "fdic_cert": 16250,  "cik": None},
    "SBKO":    {"name": "Summit Bank Group, Inc.",                       "fdic_cert": 57706,  "cik": None},
    "UBAB":    {"name": "United Bancorporation of Alabama, Inc.",        "fdic_cert": 58,     "cik": None},
    "TRCY":    {"name": "Tri City Bankshares Corporation",               "fdic_cert": 18922,  "cik": None},
    "SFIGA":   {"name": "STAR Financial Group, Inc.",                    "fdic_cert": 27235,  "cik": None},
    "TYCB":    {"name": "Calvin B. Taylor Bankshares, Inc.",             "fdic_cert": 5874,   "cik": None},
    "MSWV":    {"name": "Main Street Financial Services Corp.",          "fdic_cert": 29847,  "cik": None},
    "BKUTK":   {"name": "Bank of Utica",                                 "fdic_cert": 13397,  "cik": None},
    "ARBV":    {"name": "American Riviera Bancorp",                      "fdic_cert": 58281,  "cik": None},
    "PBNC":    {"name": "PB Financial Corporation",                      "fdic_cert": 58239,  "cik": None},
    "PONT":    {"name": "Pontiac Bancorp, Inc.",                         "fdic_cert": 16982,  "cik": None},
    # ── §12(i) / SEC-index gap banks, $100–150M tranche (sweep 2026-06-30) ─
    # Same class as the block above, extended down to $100M mkt cap: 30 more
    # banks. FXLG ("FS Bancorp NM" per the FMP screener) CLOSED 2026-07-10:
    # a full census of all 29 ACTIVE New Mexico institutions shows NO such
    # holdco, and FXLG is absent from SEC's ticker index — the screener row
    # was bad FMP metadata. Permanently omitted (better omitted than wrong);
    # don't re-attempt without new evidence of a real entity.
    # Each cert verified ACTIVE + matched on holding-company name; several
    # required state-filtered re-lookup (PPBN=Pinnacle Bankshares VA not
    # Pinnacle Financial TN; PBNK=Pinnacle Bank Gilroy CA; CNBW=CNB Corp/SC
    # Conway not CNB Financial PA). ALL cik=None — see the note above; the
    # CIKs first attached here had 3-14 yr stale XBRL, so FDIC-only is correct.
    "SOMC":   {"name": "Southern Michigan Bancorp, Inc.",               "fdic_cert": 5019,   "cik": None},
    # FMBN is the IOWA Farmers & Merchants Bancshares (Burlington; F&M Bank &
    # Trust, cert 13737) — cert 1895 is the MARYLAND same-name company, which
    # trades as FMFG (SEC cik 1698022). Sweep 2026-07-09.
    "FMBN":   {"name": "Farmers & Merchants Bancshares, Inc. (IA)",      "fdic_cert": 13737,  "cik": None},
    "DIMC":   {"name": "Dimeco, Inc.",                                  "fdic_cert": 9888,   "cik": None},
    "PRMY":   {"name": "Primary Bank",                                  "fdic_cert": 59086,  "cik": None},
    "CMRB":   {"name": "First Commerce Bank",                           "fdic_cert": 58054,  "cik": None},
    "FFDF":   {"name": "FFD Financial Corporation",                     "fdic_cert": 29787,  "cik": None},
    "CBBI":   {"name": "CBB Bancorp, Inc.",                             "fdic_cert": 57873,  "cik": None},
    "BNCC":   {"name": "BNCCORP, Inc.",                                 "fdic_cert": 57197,  "cik": None},
    "BLHK":   {"name": "Blueharbor Bank",                               "fdic_cert": 58691,  "cik": None},
    "CNBW":   {"name": "CNB Corp.",                                     "fdic_cert": 2102,   "cik": None},
    "PBCO":   {"name": "PBCO Financial Corporation",                    "fdic_cert": 34685,  "cik": None},
    "BBNA":   {"name": "Bonvenu Bancorp, Inc.",                         "fdic_cert": 26381,  "cik": None},
    "CHBH":   {"name": "Croghan Bancshares, Inc.",                      "fdic_cert": 13341,  "cik": None},
    "PPBN":   {"name": "Pinnacle Bankshares Corporation",               "fdic_cert": 6811,   "cik": None},
    "JFBC":   {"name": "Jeffersonville Bancorp",                        "fdic_cert": 7123,   "cik": None},
    "JDVB":   {"name": "JD Bancshares, Inc.",                           "fdic_cert": 16546,  "cik": None},
    "AMBK":   {"name": "American Bank Incorporated",                    "fdic_cert": 34422,  "cik": None},
    "CWBK":   {"name": "CW Bancorp",                                    "fdic_cert": 57176,  "cik": None},
    "CNBP":   {"name": "Cornerstone Bancorp Inc.",                      "fdic_cert": 57061,  "cik": None},
    "KTHN":   {"name": "Katahdin Bankshares Corp.",                     "fdic_cert": 12874,  "cik": None},
    "MPCB":   {"name": "Mountain Pacific Bancorp Inc",                  "fdic_cert": 58341,  "cik": None},
    "PBNK":   {"name": "Pinnacle Bank",                                 "fdic_cert": 58297,  "cik": None},
    "OXBC":   {"name": "Oxford Bank Corporation",                       "fdic_cert": 9719,   "cik": None},
    "PPLL":   {"name": "Peoples Ltd.",                                  "fdic_cert": 444,    "cik": None},
    "TYBT":   {"name": "Trinity Bank, N.A.",                            "fdic_cert": 57543,  "cik": None},
    "BORT":   {"name": "Bank of Botetourt",                             "fdic_cert": 6137,   "cik": None},
    "OFED":   {"name": "Oconee Federal Financial Corp.",                "fdic_cert": 30111,  "cik": None},
    "BYLB":   {"name": "Boyle Bancorp, Inc.",                           "fdic_cert": 2740,   "cik": None},
    "CNBB":   {"name": "CNB Community Bancorp, Inc.",                   "fdic_cert": 14073,  "cik": None},
    "FTFI":   {"name": "First Berlin Bancorp, Inc.",                    "fdic_cert": 5286,   "cik": None},
    "BANR":  {"name": "Banner Corp.",                       "fdic_cert": 28489,  "cik": 946673},
    # MCBI (Mountain Commerce Bancshares) was acquired 04/01/2026 — FDIC
    # cert 4931 is ACTIVE=0. The universe filter would drop it anyway via
    # cert_is_active() in data/fdic_client.py, but keeping it here as an
    # explicit None signals "we know about this; intentionally excluded".
    "MCBI":  {"name": "Mountain Commerce Bancshares (acquired)", "fdic_cert": None, "cik": None},
    # cert 17773 was Blue Ridge Bank of SOUTH CAROLINA ($195M, hcr BLUE RIDGE
    # FINANCIAL CORP) — this BANK_MAP override was beating the correct value
    # already sitting in bank_map_resolved.json. Real sub = Blue Ridge Bank NA
    # (VA) cert 35274 ($2.40B vs the $2.41B holdco), hcr BLUE RIDGE BANKSHARES INC.
    "BRBS":  {"name": "Blue Ridge Bankshares",              "fdic_cert": 35274,  "cik": 842717},
    "FSBW":  {"name": "FS Bancorp Inc.",                    "fdic_cert": 57633,  "cik": 1530249},
    "SPFI":  {"name": "South Plains Financial Inc.",        "fdic_cert": 25103,  "cik": 1163668},
    "ALRS":  {"name": "Alerus Financial Corp.",             "fdic_cert": 3931,   "cik": 903419},
    # Cert 3732 was "Farmers National Bank" of Prophetstown IL (a different
    # company). FMNB's bank = The Farmers National Bank of Canfield OH, whose
    # FDIC NAMEHCR is literally FARMERS NATIONAL BANC CORP (sweep 2026-07-09).
    "FMNB":  {"name": "Farmers National Banc Corp.",        "fdic_cert": 6540,   "cik": 709337},
    "HFWA":  {"name": "Heritage Financial Corp.",           "fdic_cert": 29012,  "cik": 1046025},
    "BAFN":  {"name": "BayFirst Financial Corp.",           "fdic_cert": 34997,  "cik": 1649739},
    "CBAN":  {"name": "Colony Bankcorp Inc.",               "fdic_cert": 22257,  "cik": 711669},
    "OVBC":  {"name": "Ohio Valley Banc Corp.",             "fdic_cert": 384,    "cik": 894671},
    "FRME":  {"name": "First Merchants Corp.",              "fdic_cert": 4365,   "cik": 712534},
    # LINKBANCORP's sub is LINKBANK (cert 14863). Cert 9889 is Mid Penn Bank.
    "LNKB":  {"name": "LINKBANCORP Inc.",                   "fdic_cert": 14863,  "cik": 1756701},
    "WAL":   {"name": "Western Alliance Bancorporation",    "fdic_cert": 57512,  "cik": 1212545},
    "TSBK":  {"name": "Timberland Bancorp",                 "fdic_cert": 28453,  "cik": 1046050},
    "BKU":   {"name": "BankUnited Inc.",                    "fdic_cert": 58979,  "cik": 1504008},
    "PGC":   {"name": "Peapack-Gladstone Financial",        "fdic_cert": 11035,  "cik": 1050743},
    "SBFG":  {"name": "SB Financial Group",                 "fdic_cert": 13339,  "cik": 767405},
    "FNWB":  {"name": "First Northwest Bancorp",            "fdic_cert": 28405,  "cik": 1556727},
    # Ticker INBC is InBankshares, Corp. (OTCQX; InBank, Raton NM, cert 11492,
    # NAMEHCR INBANKSHARES CORP). The old entry duplicated INDB — "Independent
    # Bank Corp." with Rockland Trust's cert 9712 — so INBC pages showed
    # Rockland's data. Rockland Trust's parent trades as INDB. Not SEC-listed
    # → cik None (FDIC-only path).
    "INBC":  {"name": "InBankshares, Corp.",                "fdic_cert": 11492,  "cik": None},
    # SEC-dark (Form 15-15D; growth-gate staleness catch 2026-07-16): the CIK
    # stopped financial filings — cik None forces the honest FDIC-only path.
    "CCNB":  {"name": "Coastal Carolina Bancshares",        "fdic_cert": 58864,  "cik": None},
    "JMSB":  {"name": "John Marshall Bancorp",              "fdic_cert": 58243,  "cik": 1710482},
    "RVSB":  {"name": "Riverview Bancorp Inc.",             "fdic_cert": 29922,  "cik": 1041368},
    "SLBK":  {"name": "Skyline Bankshares",                 "fdic_cert": 6861,   "cik": 1657642},
    "INBK":  {"name": "First Internet Bancorp",             "fdic_cert": 34607,  "cik": 1562463},
    "RMBI":  {"name": "Richmond Mutual Bancorporation",     "fdic_cert": 28533,  "cik": 1767837},
    "TFSL":  {"name": "TFS Financial Corp.",                "fdic_cert": 30012,  "cik": 1381668},
    "CBK":   {"name": "Commercial Bancgroup Inc.",          "fdic_cert": None,   "cik": 1981546},
    # IBTN is "InsCorp, Inc." (not iBank Financial). OTC-only, no SEC XBRL.
    # FDIC cert 35521 = InsBank, holdco INSCORP INC, TN.
    "IBTN":  {"name": "InsCorp, Inc.",                      "fdic_cert": 35521,  "cik": None},
    "FGBI":  {"name": "First Guaranty Bancshares",          "fdic_cert": 14028,  "cik": 1408534},
    "PNFP":  {"name": "Pinnacle Financial Partners",        "fdic_cert": 35583,  "cik": 2082866},
    # OTC-traded community bank — not in SEC's exchange-listed tickers.json
    # but trades as CMHF with CIK 1792597 (sub-bank: Middletown Valley Bank MD)
    "CMHF":  {"name": "Community Heritage Financial, Inc.",  "fdic_cert": 14017,  "cik": 1792597},
    # Bank OZK is a National Bank (no holding company) — files Call Reports
    # with FFIEC only, no SEC XBRL filings. cik=None forces FDIC-only path.
    "OZK":   {"name": "Bank OZK",                           "fdic_cert": 110,    "cik": None},
    "FHN":   {"name": "First Horizon Corp.",                "fdic_cert": 4977,   "cik": 36966},
    "UBSI":  {"name": "United Bankshares Inc.",             "fdic_cert": 22858,  "cik": 729986},
    "FBNC":  {"name": "First Bancorp (NC)",                 "fdic_cert": 15019,  "cik": 811589},
    "FFWM":  {"name": "First Foundation Inc.",              "fdic_cert": 58647,  "cik": 1413837},
    # Cert 19440 was a $246M Bessemer AL bank (HCR: an unrelated ESOP). FFIN's
    # lead bank = First Financial Bank, Abilene TX, $15.3B, NAMEHCR FIRST
    # FINANCIAL BANKSHARES INC (sweep 2026-07-09).
    "FFIN":  {"name": "First Financial Bankshares",         "fdic_cert": 3066,   "cik": 36029},
    "HOMB":  {"name": "Home BancShares Inc.",               "fdic_cert": 11241,  "cik": 1331520},
    "EGBN":  {"name": "Eagle Bancorp Inc.",                 "fdic_cert": 34742,  "cik": 1050441},
    "ISBA":  {"name": "Isabella Bank Corp.",                "fdic_cert": 1005,   "cik": 842517},
    "BANC":  {"name": "Banc of California Inc.",            "fdic_cert": 24045,  "cik": 1169770},
    "FLG":   {"name": "Flagstar Financial Inc.",            "fdic_cert": 32541,  "cik": 910073},
    "VLY":   {"name": "Valley National Bancorp",            "fdic_cert": 9396,   "cik": 714310},
    "KEY":   {"name": "KeyCorp",                            "fdic_cert": 17534,  "cik": 91576},
    "HBAN":  {"name": "Huntington Bancshares",              "fdic_cert": 6560,   "cik": 49196},
    "ZION":  {"name": "Zions Bancorporation",               "fdic_cert": 2270,   "cik": 109380},
    # Cert 2107 was First National Bank of SOUTH CAROLINA (Holly Hill SC,
    # $310M — its holdco is a different, private "FNB Corp"). NYSE FNB =
    # F.N.B. Corp (PA); its bank = First National Bank of Pennsylvania,
    # cert 7888, $50.4B, NAMEHCR F N B CORP (sweep 2026-07-09).
    "FNB":   {"name": "FNB Corp.",                          "fdic_cert": 7888,   "cik": 37808},
    # OZK is defined above as cik=None (National Bank, no SEC XBRL).
    # Cert 32469 is UCBH's failed predecessor. East West Bank's real cert is 31628.
    # CIK 806279 was wrong (another entity). Official SEC CIK for EWBC is 1069157.
    "EWBC":  {"name": "East West Bancorp",                  "fdic_cert": 31628,  "cik": 1069157},
    "CATY":  {"name": "Cathay General Bancorp",             "fdic_cert": 18503,  "cik": 861842},
    # Post-Umpqua merger (Mar 2023) the official SEC CIK is 887343, not 1166928.
    "COLB":  {"name": "Columbia Banking System",            "fdic_cert": 17266,  "cik": 887343},
    "BOKF":  {"name": "BOK Financial Corp.",                "fdic_cert": 4214,   "cik": 875357},
    "BOH":   {"name": "Bank of Hawaii Corp.",               "fdic_cert": 18053,  "cik": 46195},

    # ── Wrong-entity joins fixed by the FDIC NAMEHCR sweep (2026-07-09) ────
    # Each ticker below was fuzzy-joined to ANOTHER bank's cert (its pages
    # served that bank's FDIC data). Every cert here was verified against the
    # FDIC institution's own NAMEHCR (regulatory high holder) matching the
    # SEC registrant. Duplicate-cert claims were the tell: e.g. CFG, FCBM and
    # FCNCA all claimed 11063 (First-Citizens' bank).
    "CFG":   {"name": "Citizens Financial Group",           "fdic_cert": 57957,  "cik": 759944},   # was 11063 = First-Citizens (FCNCA)
    "BNY":   {"name": "Bank of New York Mellon Corp",       "fdic_cert": 639,    "cik": 1390777},  # was 3510 = Bank of America NA
    "MBIN":  {"name": "Merchants Bancorp",                  "fdic_cert": 8056,   "cik": 1629019},  # was 4365 = First Merchants (FRME)
    "FMCB":  {"name": "Farmers & Merchants Bancorp",        "fdic_cert": 1331,   "cik": 1085913},  # Lodi CA; was 6540 = Canfield OH (FMNB)
    "FMFG":  {"name": "Farmers & Merchants Bancshares",     "fdic_cert": 1895,   "cik": 1698022},  # Upperco MD; was 6540 = Canfield OH (FMNB)
    "CTBI":  {"name": "Community Trust Bancorp",            "fdic_cert": 2720,   "cik": 350852},   # Pikeville KY; was 6989 = Community Bank NA (CBU)
    "FCBM":  {"name": "First Carolina Financial Services",  "fdic_cert": 35530,  "cik": 1531193},  # Rocky Mount NC; was 11063 = First-Citizens (FCNCA)
    "HBCP":  {"name": "Home Bancorp",                       "fdic_cert": 28094,  "cik": 1436425},  # Lafayette LA; was 11241 = Centennial (HOMB)
    "HFBL":  {"name": "Home Federal Bancorp, Inc. of Louisiana", "fdic_cert": 27654, "cik": 1500375},  # Shreveport LA; was 11241 = Centennial (HOMB)
    "UBCP":  {"name": "United Bancorp",                     "fdic_cert": 9463,   "cik": 731653},   # Martins Ferry OH; was 22858 = United Bank (UBSI)
    # cik None 2026-07-16: filed Form 15-12G (SEC-dark; growth-gate catch).
    "UBOH":  {"name": "United Bancshares Inc/OH",           "fdic_cert": 12969,  "cik": None},  # Columbus Grove OH; was 22858 = United Bank (UBSI)
    "BCAL":  {"name": "California BanCorp",                 "fdic_cert": 57044,  "cik": 1795815},  # San Diego; was 24045 = Banc of California (BANC)
    "FCBC":  {"name": "First Community Bankshares",         "fdic_cert": 13012,  "cik": 859070},   # Bluefield VA; was 3850 = Xenia IL namesake ($57M)
    # FBSI (First Bancshares Inc /MO/): its bank First Home Bank (Mountain
    # Grove MO, cert 30364) has been INACTIVE since 10/2017 — the company is
    # defunct; the fuzzy join grabbed Centier Bank's cert (12854, a $10B
    # Indiana bank whose PRIVATE holdco is also named "First Bancshares Inc").
    # All-None = intentionally excluded (also in _SKIP_TICKERS).
    "FBSI":  {"name": "First Bancshares Inc /MO/ (defunct)", "fdic_cert": None,  "cik": None},

    # OTC-traded thrift: SEC CIK 942895 has no XBRL data, files only D + 13G.
    # FDIC cert 31028 = HomeTown Bank, MN (holdco REDWOOD FINANCIAL INC).
    "REDW":  {"name": "Redwood Financial Inc /MN/",         "fdic_cert": 31028,  "cik": None},

    # ── Small/thrift banks where the dynamic FDIC resolver mis-matches ──
    # These names collide with larger banks and the Jaccard-similarity
    # search picks the wrong sub-bank. Hardcoded to prevent regression.
    "IBCP":  {"name": "Independent Bank Corp. (MI)",        "fdic_cert": 27811,  "cik": 39311},    # NOT 9712 (Rockland Trust)
    "FMAO":  {"name": "Farmers & Merchants Bancorp (OH)",   "fdic_cert": 5969,   "cik": 792966},   # NOT 13421 (Union Bank Trust NE)
    "FBLA":  {"name": "FB Bancorp (MD)",                    "fdic_cert": None,   "cik": 2013639},  # Recent IPO; no FDIC match
    "MGNO":  {"name": "Magnolia Bancorp",                   "fdic_cert": None,   "cik": 2033615},  # Recent IPO; no FDIC match

    # ── Large US banks (for reference/comparison) ──────────────────────
    "JPM":   {"name": "JPMorgan Chase & Co.",               "fdic_cert": 628,    "cik": 19617},
    "BAC":   {"name": "Bank of America Corp.",              "fdic_cert": 3510,   "cik": 70858},
    "WFC":   {"name": "Wells Fargo & Co.",                  "fdic_cert": 3511,   "cik": 72971},
    "C":     {"name": "Citigroup Inc.",                     "fdic_cert": 7213,   "cik": 831001},
    "USB":   {"name": "U.S. Bancorp",                       "fdic_cert": 6548,   "cik": 36104},
    "PNC":   {"name": "PNC Financial Services",             "fdic_cert": 6384,   "cik": 713676},
    "TFC":   {"name": "Truist Financial Corp.",              "fdic_cert": 9846,   "cik": 92230},
    "COF":   {"name": "Capital One Financial",               "fdic_cert": 4297,   "cik": 927628},
    "GS":    {"name": "Goldman Sachs Group",                 "fdic_cert": 33124,  "cik": 886982},
    "MS":    {"name": "Morgan Stanley",                      "fdic_cert": 32992,  "cik": 895421},
}


# ── IR page URLs (separate to keep BANK_MAP clean) ──────────────────────
# Maps ticker -> investor relations URL. Not every bank is listed; the UI
# falls back to the SEC EDGAR company page when missing.
IR_URLS = {
    "PFS":   "https://investorrelations.provident.bank/",
    "SFST":  "https://www.southernfirst.com/investor-relations",
    "CFFI":  "https://www.cffc.com/investor-relations/",
    "CBNK":  "https://ir.capitalbankmd.com/",
    "FBIZ":  "https://ir.firstbusiness.bank/",
    "CCBG":  "https://www.ccbg.com/investor-relations/",
    "IBOC":  "https://www.ibc.com/investors",
    "CARE":  "https://www.carterbankshares.com/investor-relations/",
    "RNST":  "https://investors.renasant.com/",
    "HTB":   "https://ir.htb.com/",
    "SMBK":  "https://ir.smartfinancialinc.com/",
    "BFST":  "https://ir.b1bank.com/",
    "TCBX":  "https://ir.thirdcoast.bank/",
    "FMBH":  "https://www.firstmidbancshares.com/investor-relations/",
    "HBNC":  "https://investor.horizonbank.com/",
    "PLBC":  "https://www.plumasbank.com/investor-relations",
    "BANR":  "https://www.bannerbank.com/investor-relations",
    "BRBS":  "https://www.mybrb.com/investor-relations/",
    "FSBW":  "https://ir.fsbwa.com/",
    "SPFI":  "https://ir.southplains.com/",
    "ALRS":  "https://ir.alerus.com/",
    "FMNB":  "https://www.farmersbankgroup.com/investor-relations",
    "HFWA":  "https://ir.hf-wa.com/",
    "CBAN":  "https://ir.colony.bank/",
    # Q4 IR site the nightly subdomain probe should have found off the FDIC
    # webaddr but didn't (missing/mismatched webaddr or a transient Q4-detect
    # miss). Curated as the reliable fix — without it CBSH's first-party releases
    # (the Nolan acquisition, dividends, buybacks) reached only Google News,
    # which the Home feed hides. Verified: Q4 API returns the releases.
    "CBSH":  "https://investor.commercebank.com/",
    "FRME":  "https://www.firstmerchants.com/investor-relations",
    "WAL":   "https://ir.westernalliancebancorporation.com/",
    "BKU":   "https://ir.bankunited.com/",
    "PGC":   "https://www.pgbank.com/investor-relations",
    "INBK":  "https://ir.firstib.com/",
    "FGBI":  "https://www.firstguaranty.com/investor-relations",
    "PNFP":  "https://ir.pnfp.com/",
    "OZK":   "https://ir.ozk.com/",
    "FHN":   "https://ir.firsthorizon.com/",
    "UBSI":  "https://www.ubsi-wv.com/investor-relations",
    "FBNC":  "https://ir.localfirstbank.com/",
    "FFWM":  "https://ir.firstfoundationinc.com/",
    "FFIN":  "https://www.ffin.com/investor-relations",
    "HOMB":  "https://ir.homebancshares.com/",
    "EGBN":  "https://ir.eaglebankcorp.com/",
    "BANC":  "https://ir.bancofcal.com/",
    "FLG":   "https://ir.flagstar.com/",
    # Q4 host, NOT the valley.com marketing page — the curated marketing URL
    # suppressed Q4 discovery and cost VLY its call info (2026-07-20).
    "VLY":   "https://ir.valleynationalbank.com",
    "KEY":   "https://ir.key.com/",
    "HBAN":  "https://ir.huntington.com/",
    "ZION":  "https://www.zionsbancorporation.com/investor-relations",
    "JPM":   "https://www.jpmorganchase.com/ir",
    "BAC":   "https://investor.bankofamerica.com/",
    "WFC":   "https://www.wellsfargo.com/about/investor-relations/",
    "C":     "https://www.citigroup.com/global/investors",
    "USB":   "https://ir.usbank.com/",
    "PNC":   "https://investor.pnc.com/",
    "TFC":   "https://ir.truist.com/",
    "COF":   "https://ir.capitalone.com/",
    "GS":    "https://www.goldmansachs.com/investor-relations/",
    "MS":    "https://www.morganstanley.com/about-us-ir",
    # Q4 IR site on a holdco domain that differs from the FDIC bank WEBADDR, so
    # auto-discovery (which derives the host from WEBADDR) never reaches it.
    "STBA":  "https://www.stbancorp.com/",
    # IRapp / BusinessWire platform (RSS at /news-events/press-releases/rss).
    "AUB":   "https://investors.atlanticunionbank.com/",
}


def get_ir_url(ticker: str) -> str | None:
    """Return the IR page URL for a ticker, or None if unknown."""
    return IR_URLS.get(ticker.upper())


def get_bank_info(ticker: str) -> dict | None:
    """Return bank info dict for a ticker, same priority order as
    get_fdic_cert(). Live resolution is the LAST resort — it makes network
    calls and must never run for tickers the snapshot already covers."""
    ticker = ticker.upper()
    info = (BANK_MAP.get(ticker) or _RESOLVED_FROM_JSON.get(ticker)
            or _universe_snapshot_map().get(ticker) or _RESOLVED_CACHE.get(ticker))
    if info:
        return info
    resolved = resolve_ticker(ticker)
    return resolved if resolved.get("cik") or resolved.get("fdic_cert") else None


def get_name(ticker: str) -> str:
    """Return bank display name, same priority order as get_fdic_cert().
    Called per option by the company picker's format_func — a live
    resolution here ran 60+ network lookups per page run (measured: the
    page hung for minutes in search_fdic_by_name).

    Every name is normalized through utils.formatting.format_bank_name so the
    whole dashboard is consistent regardless of which source (ALL-CAPS SEC
    EDGAR, curated Title Case, FDIC with /XX/ suffixes) supplied it."""
    from utils.formatting import format_bank_name  # lazy: keep cold-start light
    ticker = ticker.upper()
    info = (BANK_MAP.get(ticker) or _RESOLVED_FROM_JSON.get(ticker)
            or _universe_snapshot_map().get(ticker) or _RESOLVED_CACHE.get(ticker))
    if info and info.get("name"):
        return format_bank_name(info["name"], ticker)
    resolved = resolve_ticker(ticker)
    return format_bank_name(resolved.get("name", ticker), ticker)


def get_fdic_cert(ticker: str) -> int | None:
    """
    Return FDIC cert number, in priority order:
      1. BANK_MAP (hand-curated overrides — wins even if value is None)
      2. _RESOLVED_FROM_JSON (auto-generated, committed file)
      3. universe snapshot (discovery already verified CIK/cert — one cheap
         DB read per process, no network; rebuilt nightly)
      4. _RESOLVED_CACHE (this-session live resolver results)
      5. resolve_ticker() (live SEC + FDIC lookup)
    """
    ticker = ticker.upper()
    if ticker in BANK_MAP:
        return BANK_MAP[ticker].get("fdic_cert")
    if ticker in _RESOLVED_FROM_JSON:
        return _RESOLVED_FROM_JSON[ticker].get("fdic_cert")
    snap = _universe_snapshot_map()
    if ticker in snap:
        return snap[ticker].get("fdic_cert")
    if ticker in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[ticker].get("fdic_cert")
    resolved = resolve_ticker(ticker)
    return resolved.get("fdic_cert")


def get_cik(ticker: str) -> int | None:
    """Return SEC CIK, in the same priority order as get_fdic_cert()."""
    ticker = ticker.upper()
    if ticker in BANK_MAP:
        return BANK_MAP[ticker].get("cik")
    if ticker in _RESOLVED_FROM_JSON:
        return _RESOLVED_FROM_JSON[ticker].get("cik")
    snap = _universe_snapshot_map()
    if ticker in snap:
        return snap[ticker].get("cik")
    if ticker in _RESOLVED_CACHE:
        return _RESOLVED_CACHE[ticker].get("cik")
    resolved = resolve_ticker(ticker)
    return resolved.get("cik")


# Universe-snapshot lookup tier. Discovery (data/bank_universe.py) verifies
# every ticker's CIK (SEC SIC + US-domicile check) and FDIC cert before
# persisting, so the snapshot is an authoritative resolved store for tickers
# beyond the curated files. Without this tier, each newly discovered bank
# triggered a live per-ticker SEC resolution in EVERY fresh process —
# measured 174s for the universe list on a cold start. Read directly from
# data.cache (not bank_universe) to avoid a circular import.
_SNAPSHOT_MAP: dict[str, dict] | None = None


def _universe_snapshot_map() -> dict[str, dict]:
    global _SNAPSHOT_MAP
    if _SNAPSHOT_MAP is None:
        try:
            from data import cache
            # max_age_s=None: the snapshot resolves tickers at any age (the
            # nightly job owns refresh); the store's default 24h TTL would
            # blank this tier whenever the job ran late.
            snap = cache.get("bank_universe_lastgood", max_age_s=None) or {}
            uni = snap.get("universe", snap)  # stamped or legacy format
            found = {
                t: v for t, v in (uni or {}).items() if isinstance(v, dict)
            }
            if not found:
                # No snapshot yet (fresh DB) — retry on the next call rather
                # than pinning this tier empty for the process lifetime.
                return {}
            _SNAPSHOT_MAP = found
        except Exception as e:
            print(f"[bank_mapping] snapshot tier unavailable: {type(e).__name__}: {e}")
            return {}  # transient (DB hiccup) — retry on the next call
    return _SNAPSHOT_MAP


# ── Runtime cache for dynamically resolved tickers ───────────────────────
# Tickers added at runtime that aren't in BANK_MAP get resolved once
# via SEC/FDIC API lookups and cached here for the session.
_RESOLVED_CACHE: dict[str, dict] = {}


def search_sec_by_ticker(ticker: str) -> tuple[int | None, str | None]:
    """
    Look up SEC CIK and company name by ticker using company_tickers.json.
    Returns (cik, company_name) tuple.
    """
    try:
        url = "https://www.sec.gov/files/company_tickers.json"
        headers = {"User-Agent": "BankValuationDashboard admin@company.com"}
        resp = requests.get(url, headers=headers, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        ticker_upper = ticker.upper()
        for entry in data.values():
            if entry.get("ticker", "").upper() == ticker_upper:
                return entry.get("cik_str"), entry.get("title", "")
        return None, None
    except Exception:
        return None, None


# Suffix WORDS dropped for matching — token-based, never substring (2026-07-10):
# the old substring replace glued names: " CORP" ate the middle of
# " CORPORATION" ("…BANKSHARESORATION") and " CO" the head of " COMMUNITY"/
# " COMPANY"/" COLUMBIA" ("MMUNITY…"), corrupting the Jaccard word sets. It
# mostly "worked" only because BOTH sides of a comparison were corrupted
# identically.
_SUFFIX_WORDS = {"INC", "CORP", "CO", "LTD", "CORPORATION", "HOLDINGS",
                 "FINANCIAL", "BANCORP", "BANCORPORATION", "GROUP", "LLC"}


def _clean_name(name: str) -> str:
    """Normalize a holding-company name for matching."""
    if not name:
        return ""
    s = name.upper()
    for state_tag in ["/DE", "/MD", "/NJ", "/RI", "/PA", "/OH", "/NC"]:
        s = s.replace(state_tag, "")
    # Strip punctuation, then drop suffix words at TOKEN boundaries.
    for p in [",", ".", "'", "&"]:
        s = s.replace(p, " ")
    return " ".join(w for w in s.split() if w not in _SUFFIX_WORDS)


def _name_similarity(a: str, b: str) -> float:
    """
    Jaccard similarity of cleaned-name word sets. 1.0 = identical word set.
    Avoids 'starts-with' false positives that matched everything to BAC.
    """
    wa = set(_clean_name(a).split())
    wb = set(_clean_name(b).split())
    if not wa or not wb:
        return 0.0
    # Ignore trivial words that match everything
    trivial = {"BANK", "BANKS", "BK", "BANCORP", "BANCORPORATION",
               "THE", "A", "AN", "OF"}
    wa -= trivial
    wb -= trivial
    if not wa or not wb:
        # If both names are only trivial words, fall back to exact-ish match
        return 1.0 if _clean_name(a) == _clean_name(b) else 0.0
    return len(wa & wb) / len(wa | wb)


def search_fdic_by_name(name: str, min_similarity: float = 0.5,
                        profile: dict | None = None) -> int | None:
    """
    Search FDIC for the primary bank subsidiary CERT matching a holding-
    company name, in the state the registrant actually files from.

    Strategy:
      1. Build 1-3 quoted-phrase queries from the cleaned name (the FDIC API
         treats bare spaces as OR, so we MUST quote phrases to search exact
         substrings).
      2. Run each query against the FDIC institutions endpoint (sorted by
         ASSET DESC) and collect candidate banks.
      3. Drop candidates whose state contradicts the registrant's (`profile`,
         as returned by _profile_from_submissions / get_filing_info). A name
         is not an identity: "COMMERCE BANCSHARES INC" is the high holder of
         both a $35.5B Missouri bank and an $88M Louisiana one, and name
         similarity scores them IDENTICALLY. Skipped when no profile is
         given — a caller with no state cannot do better than the name.
      4. Score the survivors by name similarity to the query.
      5. Return the highest-similarity match above `min_similarity`;
         otherwise return None rather than wire up the wrong cert.

    This replaces an earlier implementation that did a single-word wildcard
    search which silently fell through to BAC (cert=3510) for many small banks.
    """
    if not name:
        return None

    try:
        clean = _clean_name(name)
        if not clean:
            return None
        words = clean.split()

        # Build candidate quoted phrases in order of specificity.
        # For "ATLANTIC UNION BANKSHARES" we'd try:
        #   "ATLANTIC UNION BANKSHARES"  (most specific — might not match)
        #   "ATLANTIC UNION"
        #   "ATLANTIC"
        phrases = []
        if len(words) >= 3:
            phrases.append(" ".join(words[:3]))
        if len(words) >= 2:
            phrases.append(" ".join(words[:2]))
        if words:
            # Avoid single-word generic first words that would match too broadly
            generic_singletons = {
                "BANK", "FIRST", "NATIONAL", "AMERICAN", "UNITED", "CITIZENS",
                "COMMUNITY", "PEOPLES", "HERITAGE", "HOME", "CENTRAL",
                "SOUTHERN", "NORTHERN", "EASTERN", "WESTERN", "PACIFIC",
                "SUMMIT", "PREMIER", "INDEPENDENT", "TRUST", "THE",
            }
            if words[0] not in generic_singletons:
                phrases.append(words[0])

        # Dedupe while preserving order
        seen = set(); phrases = [p for p in phrases if not (p in seen or seen.add(p))]

        all_candidates = []
        for phrase in phrases:
            # Quote the phrase (bare spaces are OR to the FDIC API) but do NOT
            # pre-encode it: requests URL-encodes params exactly once, so a
            # urllib.parse.quote() here double-encodes ("%2522...") and the
            # phrase filter matches nothing (audit P3).
            params = {
                "filters": f'NAMEHCR:"{phrase}"',
                "fields": "CERT,NAME,NAMEHCR,ASSET,ACTIVE,STALP,STALPHCR",
                "sort_by": "ASSET",
                "sort_order": "DESC",
                "limit": 20,
            }
            try:
                resp = requests.get(
                    "https://banks.data.fdic.gov/api/institutions",
                    params=params, timeout=10,
                )
                resp.raise_for_status()
                for cand in resp.json().get("data", []):
                    all_candidates.append(cand.get("data", {}))
            except Exception:
                continue

            # If the most specific phrase returned a confident match, stop early
            if all_candidates:
                break

        if not all_candidates:
            return None

        # Prefer ACTIVE institutions
        active = [c for c in all_candidates if c.get("ACTIVE") == 1]
        pool = active or all_candidates

        # The second key: drop same-name banks in a state the registrant has
        # no connection to. If that leaves nothing, the name matched somebody
        # else — return None rather than the best-scoring stranger.
        if profile:
            from data.bank_universe import _state_corroborates
            in_state = [c for c in pool if _state_corroborates(profile, c)]
            if not in_state:
                return None
            pool = in_state

        # Score by similarity
        best = None; best_score = 0.0
        for cand in pool:
            cand_name = cand.get("NAMEHCR", "")
            score = _name_similarity(name, cand_name)
            if score > best_score:
                best_score = score
                best = cand

        if best and best_score >= min_similarity:
            return int(best["CERT"])
        return None
    except Exception:
        return None


def resolve_ticker(ticker: str) -> dict:
    """
    Resolve a ticker to full bank info. Uses static map first, then runtime
    cache, then falls back to SEC + FDIC API lookups. Results are cached
    so subsequent calls are instant.

    Returns dict with ticker, name, fdic_cert, cik (any may be None).
    """
    ticker = ticker.upper()

    # 1. Static map
    info = BANK_MAP.get(ticker)
    if info:
        return {"ticker": ticker, **info}

    # 2. Runtime cache
    if ticker in _RESOLVED_CACHE:
        return {"ticker": ticker, **_RESOLVED_CACHE[ticker]}

    # 3. Dynamic resolution
    cik, sec_name = search_sec_by_ticker(ticker)

    # Clean up SEC name to title case
    name = sec_name.title() if sec_name else ticker
    # Fix common title-case issues
    for bad, good in [("'S", "'s"), ("Ii", "II"), ("Iii", "III"),
                      ("Llc", "LLC"), ("N.A.", "N.A.")]:
        name = name.replace(bad, good)

    # Try to find FDIC cert from the SEC company name, in the registrant's own
    # state — the name alone cannot separate same-name banks (see the
    # wrong-entity corpus in tests/test_cert_state_corrections.py). A profile
    # we can't read costs the state key, not the join.
    profile = None
    if cik:
        try:
            from data.sec_client import get_filing_info
            info_sec = get_filing_info(int(cik), max_filings=1)
            profile = {"hq_state": info_sec.get("hq_state", ""),
                       "state_of_incorp": info_sec.get("state_of_incorp", "")}
        except Exception:
            profile = None
    fdic_cert = search_fdic_by_name(sec_name, profile=profile) if sec_name else None

    resolved = {"name": name, "fdic_cert": fdic_cert, "cik": cik}
    _RESOLVED_CACHE[ticker] = resolved
    return {"ticker": ticker, **resolved}
